USE idandt_tinyforum;

CREATE TABLE posts (
  id INT NOT NULL AUTO_INCREMENT,
  id_topic INT NOT NULL,
  id_user INT NOT NULL,
  body MEDIUMTEXT NULL,
  created DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id));
