USE idandt_tinyforum;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  admin TINYINT NOT NULL DEFAULT 0,
  disabled TINYINT NOT NULL DEFAULT 0,
  avatar VARCHAR(250) NULL DEFAULT NULL,
  session_expires TIMESTAMP(3) NULL,
  PRIMARY KEY (id));

